Converted IHO S63 document
metanorma/mn-samples-iho pull request #4
Opened 2020-03-28 22:29 UTC by anermina

Questions and notes:
- I wasn't sure how to convert references, so I left References sections with mark-up as in the Introduction section.
- Issue https://github.com/metanorma/mn-samples-ogc/issues/75 is opened regarding text between "<" and ">" signs in table entries. In this document, I added additional spaces in < h20> and < space>.
- Many figures are positioned next to the text (as there are two columns, one for text and the other for figures) in the original document. Sometimes text refers to them with something like: "as illustrated across". I didn't change that text, but I suggest to add cross-references to the specific figures, i.e. to write something like "as illustrated in <<fig1>>". Please let me know if this should be done.
- Issue with duplicated titles for Examples was mentioned in https://github.com/metanorma/mn-samples-ogc/pull/36. I believe a new issue is opened for this topic (so I didn't open another one), but I couldn't find it. Due to this duplication, where title is set once after "Example" keyword and the second time as a Figure title, I marked all examples with [%unnumbered]. 
- Glossary wasn't initially added, so I just made a separate .adoc for glossary and commented "include::sections/00-glossary.adoc[]" in main .adoc.

2020-03-29 07:23 UTC, ronaldtse commented
> I wasn't sure how to convert references, so I left References sections with mark-up as in the Introduction section.

Please help convert them into the typical Metanorma format. The sources:

```
[1] S57 edition 3.1: IHO Transfer Standard for Digital Hydrographic Data, International Hydrographic Organization (www.iho.int)

[2] Digital Signature Standard (DSS), FIPS Pub 186 (www.itl.nist.gov/div897/pubs/fip186.htm)

[3] Secure Hash Standard (SHA), FIPS Pub 180-1 (www.itl.nist.gov/div897/pubs/fip180-1.htm)

[4] Information Technology – Open Systems Interconnection – The Directory: Authentication Framework. X.509 version 3 - International Telecommunication Union

[6] ZIP File Format Specification, PKWare Inc.

[7] DES Modes of Operation, FIPS Pub 81 (www.itl.nist.gov/fipspubs/fip81.htm)

[8] RFC 1423: Privacy Enhancements for Internet Electronic Mail: Part III: Algorithms, Modes and Identifiers

[9] Blowfish encryption algorithm, B. Schneier, Fast Software Encryption, Cambridge Security Workshop Proceedings (December 1993), Springer-Verlag, 1994, pp. 191-204. (www.counterpane.com)

[10] CRC32 checksum algorithm. Information technology -- Telecommunications and information exchange between systems -- High-level data link control (HDLC) procedures. ISO/IEC 13239:2002.
```

Here there are 2 types of documents: standards vs general articles.

* [1] - we treat this as a citation of an IHO standard (we need to do Relaton-IHO)
* [2], [3], [7] are NIST FIPS citations
* [4] an ITU standard citation
* [8] an IETF citation
* [6], [9] general citations
* [10] ISO standard.

(Notice the document is missing [5], I've reported it)

> Many figures are positioned next to the text (as there are two columns, one for text and the other for figures) in the original document. Sometimes text refers to them with something like: "as illustrated across". I didn't change that text, but I suggest to add cross-references to the specific figures, i.e. to write something like "as illustrated in <>". Please let me know if this should be done.

This is something we have to live with. I will seek confirmation. Can we rename those text to "as illustrated in <>" for now so we don't lose the references?

> Glossary wasn't initially added, so I just made a separate .adoc for glossary and commented "include::sections/00-glossary.adoc[]" in main .adoc.

Thanks, I probably forgot to add it!

2020-03-29 07:29 UTC, ronaldtse requested changes

2020-03-29 07:29 UTC, ronaldtse commented on sources/s63/sections/00-glossary.adoc
> +Secure Hash Algorithm [3]
@anermina once the references are converted can you change [3] to a `[.source]` block that refers to [3]? Thanks.

2020-03-29 13:31 UTC, ronaldtse commented
@anermina for citing references, you can use the "user tag format" as in:

https://www.metanorma.com/author/topics/document-format/bibliography/#named-reference-tag-with-automatic-reference-fetching

```
* [[[ISO20483,(CerMoist)ISO 20483]]], _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,(MaiMoist)ISO 6540]]]. _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
```

Maybe we can use the "numeric" form as tag too:

```
* [[[ISO20483,(1)ISO 20483]]], _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,(2)ISO 6540]]]. _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
```

?

2020-03-29 14:02 UTC, anermina commented
Thanks @ronaldtse !
Changes are made, but there are multiple commits because I unnecessarily rushed with the changes.

2020-03-29 14:45 UTC, ronaldtse requested changes
Once these requests are addressed should be good to merge. Thanks @anermina !

2020-03-29 14:45 UTC, ronaldtse commented on sources/s63/sections/01-introduction.adoc
> +* [[[dss,(2)FIPS Pub 186]]], Digital Signature Standard (DSS), FIPS Pub 186 (www.itl.nist.gov/div897/pubs/fip186.htm)
Instead of `FIPS Pub 186` you have to write `NIST FIPS 186` for auto-fetching to work.

2020-03-29 14:45 UTC, ronaldtse commented on sources/s63/sections/01-introduction.adoc
> +* [[[sha,(3)FIPS Pub 180-1]]], Secure Hash Standard (SHA), FIPS Pub 180-1 (www.itl.nist.gov/div897/pubs/fip180-1.htm)
As above.

2020-03-29 14:45 UTC, ronaldtse commented on sources/s63/sections/01-introduction.adoc
> +* [[[rfc1423,(7)RFC 1423]]], RFC 1423: Privacy Enhancements for Internet Electronic Mail: Part III: Algorithms, Modes and Identifiers
`RFC 1423` has to be `IETF RFC 1423`.

2020-03-29 14:45 UTC, ronaldtse commented on sources/s63/sections/01-introduction.adoc
> +* [[[des_mf,(6)FIPS Pub 81]]], DES Modes of Operation, FIPS Pub 81 (www.itl.nist.gov/fipspubs/fip81.htm)
As above.

2020-03-29 16:17 UTC, anermina commented
Thank you once again, @ronaldtse ! I applied these changes.

In generated document, reference numbers are repeated (yellow highlighted):
![image](https://user-images.githubusercontent.com/55683568/77854210-23ca4a80-71e9-11ea-8eef-3162610f58cc.png)

Should this be reported as an issue?

2020-03-30 01:49 UTC, ronaldtse commented
@anermina yes I think this is a bug. Can you file it in metanorma-standoc? It seems that the auto-fetch "key" (the document to be searched for) is being confused with the user-defined reference tag. Thanks!

2020-03-30 02:43 UTC, ronaldtse commented
Just filed the bug. Let's first merge this. Thanks!

2020-03-30 02:43 UTC, merged